### ISSUE TITLE
plugin crash if table revision already exists

### ISSUE THREAD

**Issue by haubourg** [Oslandia/qgis-versioning#20]
```
Une erreur est apparue lors de l'exécution du code Python :


Traceback (most recent call last):
  File "\\NAS01\appdata2008\haubourg\AppData\Roaming\.qgismaster/python/plugins\qgis_versioning\versioning.py", line 532, in historize
    versioning_base.historize( self.pg_conn_info(), schema )
  File "\\NAS01\appdata2008\haubourg\AppData\Roaming\.qgismaster/python/plugins\qgis_versioning\versioning_base.py", line 887, in historize
    pcur.execute("CREATE TABLE "+schema+".revisions ("
  File "\\NAS01\appdata2008\haubourg\AppData\Roaming\.qgismaster/python/plugins\qgis_versioning\versioning_base.py", line 63, in execute
    self.cur.execute( sql )
ProgrammingError: ERREUR:  la relation « revisions » existe déjà


```

**Comment by SebastienPeillet** [comment]
Project migrated to : https://gitlab.com/Oslandia/qgis/qgis-versioning
