### ISSUE TITLE
Add support for Primarey key on multiple columns

### ISSUE THREAD

**Issue by haubourg** [Oslandia/qgis-versioning#21]
```
Une erreur est apparue lors de l'exécution du code Python :


Traceback (most recent call last):
  File "\\NAS01\appdata2008\haubourg\AppData\Roaming\.qgismaster/python/plugins\qgis_versioning\versioning.py", line 532, in historize
    versioning_base.historize( self.pg_conn_info(), schema )
  File "\\NAS01\appdata2008\haubourg\AppData\Roaming\.qgismaster/python/plugins\qgis_versioning\versioning_base.py", line 895, in historize
    add_branch( pg_conn_info, schema, 'trunk', 'initial commit' )
  File "\\NAS01\appdata2008\haubourg\AppData\Roaming\.qgismaster/python/plugins\qgis_versioning\versioning_base.py", line 962, in add_branch
    "REFERENCES "+schema+"."+table+"("+pkey+")")
  File "\\NAS01\appdata2008\haubourg\AppData\Roaming\.qgismaster/python/plugins\qgis_versioning\versioning_base.py", line 63, in execute
    self.cur.execute( sql )
ProgrammingError: ERREUR:  il n'existe aucune contrainte unique correspondant aux clés données pour la
table « rwbody » référencée



Version de Python :
2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)]


Version de QGIS :
2.11.0-Master Master, 9ce6b6b

Chemin vers Python : ['U:/OSGEO4~1/apps/qgis-dev/./python/plugins\\processing', 'U:/OSGEO4~1/apps/qgis-dev/./python', u'\\\\NAS01\\appdata2008\\haubourg\\AppData\\Roaming\\.qgismaster/python', u'\\\\nas02\\groupe\\refgeo\\Espace_Correspondants_SIG\\Astuces_Outils\\QGISMASTER_PLUGINS', u'\\\\NAS01\\appdata2008\\haubourg\\AppData\\Roaming\\.qgismaster/python/plugins', 'U:/OSGEO4~1/apps/qgis-dev/./python/plugins', 'U:\\OSGEO4~1\\apps\\Python27\\lib\\site-packages\\matplotlib-1.3.1-py2.7-win-amd64.egg', 'U:\\OSGEO4~1\\apps\\Python27\\lib\\site-packages\\nose-1.3.3-py2.7.egg', 'U:\\OSGEO4~1\\apps\\Python27\\lib\\site-packages\\tornado-4.0.1-py2.7-win-amd64.egg', 'U:\\OSGEO4~1\\apps\\Python27\\lib\\site-packages\\backports.ssl_match_hostname-3.4.0.2-py2.7.egg', 'U:\\OSGEO4~1\\apps\\Python27\\lib\\site-packages\\certifi-14.05.14-py2.7.egg', 'c:\\osgeo4~1\\apps\\python27\\lib\\site-packages\\python_dateutil-2.1-py2.7.egg', 'c:\\osgeo4~1\\apps\\python27\\lib\\site-packages\\six-1.3.0-py2.7.egg', 'U:\\OSGEO4~1\\bin', 'U:\\OSGEO4~1\\bin\\python27.zip', 'U:\\OSGEO4~1\\apps\\Python27\\DLLs', 'U:\\OSGEO4~1\\apps\\Python27\\lib', 'U:\\OSGEO4~1\\apps\\Python27\\lib\\plat-win', 'U:\\OSGEO4~1\\apps\\Python27\\lib\\lib-tk', 'U:\\OSGEO4~1\\apps\\Python27', 'u:\\osgeo4~1\\apps\\python27\\lib\\site-packages\\jinja2-2.7.2-py2.7.egg', 'u:\\osgeo4~1\\apps\\python27\\lib\\site-packages\\markupsafe-0.23-py2.7-win-amd64.egg', 'u:\\osgeo4~1\\apps\\python27\\lib\\site-packages\\owslib-0.7.2-py2.7.egg', 'u:\\osgeo4~1\\apps\\python27\\lib\\site-packages\\pytz-2012j-py2.7.egg', 'u:\\osgeo4~1\\apps\\python27\\lib\\site-packages\\setuptools-5.4.1-py2.7.egg', 'u:\\osgeo4~1\\apps\\python27\\lib\\site-packages\\shapely-1.2.18-py2.7-win-amd64.egg', 'u:\\osgeo4~1\\apps\\python27\\lib\\site-packages\\xlrd-0.9.2-py2.7.egg', 'u:\\osgeo4~1\\apps\\python27\\lib\\site-packages\\xlwt-0.7.5-py2.7.egg', 'U:\\OSGEO4~1\\apps\\Python27\\lib\\site-packages', 'U:\\OSGEO4~1\\apps\\Python27\\lib\\site-packages\\PIL', 'U:\\OSGEO4~1\\apps\\Python27\\lib\\site-packages\\win32', 'U:\\OSGEO4~1\\apps\\Python27\\lib\\site-packages\\win32\\lib', 'U:\\OSGEO4~1\\apps\\Python27\\lib\\site-packages\\Pythonwin', 'U:\\OSGEO4~1\\apps\\Python27\\lib\\site-packages\\six-1.3.0-py2.7.egg', 'U:\\OSGEO4~1\\apps\\Python27\\lib\\site-packages\\wx-2.8-msw-unicode', u'\\\\NAS01\\appdata2008\\haubourg\\AppData\\Roaming\\.qgismaster/python', '\\\\nas02\\groupe\\refgeo\\Espace_Correspondants_SIG\\Astuces_Outils\\QGISMASTER_PLUGINS\\DigitizingTools\\tools', 'U:\\OSGEO4~1\\apps\\qgis-dev\\python\\plugins\\fTools\\tools', 'V:/temp_user']
```

**Comment by vmora** [comment]
Same comment as #22

**Comment by SebastienPeillet** [comment]
Project migrated to : https://gitlab.com/Oslandia/qgis/qgis-versioning
