### ISSUE TITLE
Add support for non integer primary key

### ISSUE THREAD

**Issue by haubourg** [Oslandia/qgis-versioning#22]
```
Traceback (most recent call last):
  File "\\NAS01\appdata2008\haubourg\AppData\Roaming\.qgismaster/python/plugins\qgis_versioning\versioning.py", line 532, in historize
    versioning_base.historize( self.pg_conn_info(), schema )
  File "\\NAS01\appdata2008\haubourg\AppData\Roaming\.qgismaster/python/plugins\qgis_versioning\versioning_base.py", line 895, in historize
    add_branch( pg_conn_info, schema, 'trunk', 'initial commit' )
  File "\\NAS01\appdata2008\haubourg\AppData\Roaming\.qgismaster/python/plugins\qgis_versioning\versioning_base.py", line 962, in add_branch
    "REFERENCES "+schema+"."+table+"("+pkey+")")
  File "\\NAS01\appdata2008\haubourg\AppData\Roaming\.qgismaster/python/plugins\qgis_versioning\versioning_base.py", line 63, in execute
    self.cur.execute( sql )
ProgrammingError: ERREUR:  la contrainte de clé étrangère « rwbody_trunk_parent_fkey » ne peut pas être implémentée
DETAIL:  Les colonnes clés « trunk_parent » et « eu_cd » sont de types incompatibles : integer et character varying.



```

**Comment by vmora** [comment]
Sorry, my sentence here http://www.oslandia.com/qgis-versioning-plugin-en.html:

    tables must have primary keys

is incomplete: tables must have single field integer primary keys.

**Comment by SebastienPeillet** [comment]
Project migrated to : https://gitlab.com/Oslandia/qgis/qgis-versioning
